// ffmpeg.js
const config = require("./env");

let transcodingSettings = {
  resolutions: [
    { name: "1080p", width: 1920, height: 1080, bitrate: 4500 },
    { name: "720p", width: 1280, height: 720, bitrate: 2500 },
    { name: "480p", width: 854, height: 480, bitrate: 1000 },
  ],
  segmentDuration: {
    lowLatency: 2,
    standardLatency: 6,
  },
};

function updateTranscodingSettings(newSettings) {
  transcodingSettings = { ...transcodingSettings, ...newSettings };
}

module.exports = {
  ffmpegPath: config.ffmpegPath,
  transcodingSettings,
  updateTranscodingSettings,
  presets: {
    hls: {
      lowLatency: [
        // 1080p
        [
          "-vf",
          "scale=w=1920:h=1080",
          "-b:v",
          "4500k",
          "-maxrate",
          "5000k",
          "-bufsize",
          "10000k",
          "-c:v",
          "libx264",
          "-preset",
          "veryfast",
          "-g",
          "48",
          "-sc_threshold",
          "0",
          "-c:a",
          "aac",
          "-ar",
          "44100",
          "-b:a",
          "192k",
          "-f",
          "hls",
          "-hls_time",
          "2",
          "-hls_playlist_type",
          "event",
          "-hls_segment_filename",
          "1080p_%03d.ts",
        ],
        // 720p
        [
          "-vf",
          "scale=w=1280:h=720",
          "-b:v",
          "2500k",
          "-maxrate",
          "3000k",
          "-bufsize",
          "6000k",
          "-c:v",
          "libx264",
          "-preset",
          "veryfast",
          "-g",
          "48",
          "-sc_threshold",
          "0",
          "-c:a",
          "aac",
          "-ar",
          "44100",
          "-b:a",
          "128k",
          "-f",
          "hls",
          "-hls_time",
          "2",
          "-hls_playlist_type",
          "event",
          "-hls_segment_filename",
          "720p_%03d.ts",
        ],
        // 480p
        [
          "-vf",
          "scale=w=854:h=480",
          "-b:v",
          "1000k",
          "-maxrate",
          "1500k",
          "-bufsize",
          "3000k",
          "-c:v",
          "libx264",
          "-preset",
          "veryfast",
          "-g",
          "48",
          "-sc_threshold",
          "0",
          "-c:a",
          "aac",
          "-ar",
          "44100",
          "-b:a",
          "96k",
          "-f",
          "hls",
          "-hls_time",
          "2",
          "-hls_playlist_type",
          "event",
          "-hls_segment_filename",
          "480p_%03d.ts",
        ],
      ],
      standardLatency: [
        // 1080p
        [
          "-vf",
          "scale=w=1920:h=1080",
          "-b:v",
          "4500k",
          "-maxrate",
          "5000k",
          "-bufsize",
          "10000k",
          "-c:v",
          "libx264",
          "-preset",
          "veryfast",
          "-g",
          "48",
          "-sc_threshold",
          "0",
          "-c:a",
          "aac",
          "-ar",
          "44100",
          "-b:a",
          "192k",
          "-f",
          "hls",
          "-hls_time",
          "6",
          "-hls_playlist_type",
          "event",
          "-hls_segment_filename",
          "1080p_%03d.ts",
        ],
        // 720p
        [
          "-vf",
          "scale=w=1280:h=720",
          "-b:v",
          "2500k",
          "-maxrate",
          "3000k",
          "-bufsize",
          "6000k",
          "-c:v",
          "libx264",
          "-preset",
          "veryfast",
          "-g",
          "48",
          "-sc_threshold",
          "0",
          "-c:a",
          "aac",
          "-ar",
          "44100",
          "-b:a",
          "128k",
          "-f",
          "hls",
          "-hls_time",
          "6",
          "-hls_playlist_type",
          "event",
          "-hls_segment_filename",
          "720p_%03d.ts",
        ],
        // 480p
        [
          "-vf",
          "scale=w=854:h=480",
          "-b:v",
          "1000k",
          "-maxrate",
          "1500k",
          "-bufsize",
          "3000k",
          "-c:v",
          "libx264",
          "-preset",
          "veryfast",
          "-g",
          "48",
          "-sc_threshold",
          "0",
          "-c:a",
          "aac",
          "-ar",
          "44100",
          "-b:a",
          "96k",
          "-f",
          "hls",
          "-hls_time",
          "6",
          "-hls_playlist_type",
          "event",
          "-hls_segment_filename",
          "480p_%03d.ts",
        ],
      ],
    },
  },
};
